# Copyright (c) 2026 Xavier Beheydt <xavier.beheydt@gmail.com>

name: docs

on:
  push:
    # not latest: it is protected, the bot cannot push there
    branches:
      - dev
    paths:
      - README.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v6.0.0
        with:
          vimdoc: mdrun
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(ci): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
